/** Legal texts (EN) — aligned with Apple App Store (Guideline 5.1.1, 5.1.1(v), Privacy Labels) and GDPR.
 *  To be reviewed by a qualified professional before production. */

const mentionsBody = `The « {{tradeName}} » service (the “Application”) covers an iOS / Android mobile application and an associated website. It is published by {{companyName}}, {{legalForm}}, with registered office at {{addressLine}}, {{country}} (the “Publisher”).

Registration: {{registrationNumber}}. EU VAT number: {{vatNumber}}.

Contact: {{contactEmail}}.

Publication director: {{publicationDirector}}.

Data hosting: personal data is stored on infrastructure operated by {{hostName}} ({{hostWebsite}}), in a European Union region as per the project configuration. Provider's registered office (regulatory information): {{hostAddress}}. The public website is hosted by Vercel Inc. (https://vercel.com).

Intellectual property: the Application's elements (texts, interface, trademarks, logos) are protected. Unauthorized reproduction or representation is prohibited.

Complaints: send your requests to {{contactEmail}}.

Governing law: French law and, where applicable, European Union law. Disputes: courts having jurisdiction over the Publisher's registered office, subject to mandatory provisions, particularly in employment and consumer law.`;

const privacyBody = `This privacy policy describes the processing of personal data within the « {{tradeName}} » service (the “Application”), covering the mobile app (iOS / Android) and the associated website. The service is published by {{companyName}} ({{contactEmail}}), acting as data controller within the meaning of Regulation (EU) 2016/679 (GDPR). The Application is intended for strictly professional use by employees and authorized collaborators of the Publisher; every account is created or validated by the Publisher.

Intended audience — Minimum age: the Application is reserved for adult professional use. The Publisher sets the minimum age of use at 16 (in line with Article 8 GDPR and French law) and discourages any use by minors outside an authorized professional setting. The Application is not designed for children.

1. Categories of data collected

The Application collects only data strictly necessary to its professional operation:
• Contact information: full name, email address (used as login identifier), professional role and department where applicable.
• Identifiers: unique user ID generated by the authentication service ({{hostName}}).
• User content: expense entries (date, supplier, net / VAT-inclusive amounts, VAT, category, associated project), photographs of receipts and uploaded supporting documents (imported from the gallery or captured via the camera), optional comments, tracked commercial projects.
• Interface preferences: chosen language (FR / EN / ZH), authentication session stored locally.
• Minimal technical diagnostics: connection logs and error messages (for security and support purposes). The Application does not embed any third-party behavioral analytics tool (no Google Analytics, no public Sentry, no Mixpanel, no advertising SDK).

2. Tracking (App Tracking Transparency)

The Publisher expressly declares that the Application **DOES NOT TRACK** its users within the meaning of Apple's App Tracking Transparency framework:
• no advertising identifier (IDFA) is read;
• no data is shared with data brokers or advertising networks;
• no correlation is made between your activity in the Application and your activity in other third-party apps or websites.
Consequently, the Application does not display the “Allow … to track you?” prompt on iOS.

3. iOS / Android permissions requested

The Application requests your explicit consent before accessing the following resources; you may refuse or revoke these accesses at any time from your device's Settings:
• Camera (NSCameraUsageDescription): to scan a receipt. Images are encrypted in transit and stored in your dedicated space.
• Photo library (NSPhotoLibraryUsageDescription): to import a previously taken supporting document. No other photo from your library is read.
On the website, camera access and file imports are not used: data entry is manual.

4. Purposes and legal bases

Data is processed for the following purposes:
• account management and authentication — legal basis: performance of the employment contract / pre-contractual measures;
• expense management (entry, validation, rejection, accounting export) — legal basis: legitimate interest of the employer in organizing professional reimbursements;
• management of commercial projects and related information — legal basis: legitimate interest;
• security, fraud and unauthorized access prevention — legal basis: legitimate interest / legal obligation;
• legal and accounting obligations — legal basis: legal obligation (notably French Commercial Code and Tax Code);
• service improvement — legal basis: legitimate interest, within proportionality limits.

5. Notifications

The Application may send in-app notifications (and, where applicable, iOS / Android push notifications) regarding the status of your expenses (validation, rejection, request for information). You can disable push notifications from your device's Settings.

6. Recipients

Data is accessible only to authorized persons:
• yourself for your own data;
• your hierarchy / finance / administration of the Publisher, within the limits of their respective roles (database-level Row-Level Security);
• the technical subprocessors listed below, acting on the Publisher's instructions.

7. Technical subprocessors

• {{hostName}} ({{hostWebsite}}) — authentication, database and storage of supporting documents, in a European Union region.
• Vercel Inc. (https://vercel.com) — hosting of the public website (legal pages, management interface).
• Google LLC / Google Gemini (https://ai.google.dev) — extraction of receipt information by artificial intelligence (image analysis). Images transit via a server-side function operated by the Publisher; the provider does not retain your supporting documents beyond the analysis time, in accordance with its retention policy.
• Apple Inc. / Google LLC — distribution of the application via App Store / Google Play (no access to your expense content).

8. Location and transfers outside the EU

Business data (expenses, supporting documents, accounts) is stored on servers located within the European Union. Some providers (Google Gemini, Apple, Google) may be located in the United States; transfers, if any, are framed by the European Commission's standard contractual clauses or an equivalent mechanism provided by the GDPR.

9. Retention periods

• Active account: as long as you are an authorized employee / collaborator.
• Supporting documents and expense entries: duration required by legal and accounting obligations (up to 10 years for accounting documents, in accordance with Article L123-22 of the French Commercial Code).
• Connection and security logs: 12 months maximum.
• Data after account deletion: see section 11.

10. Your rights (GDPR)

You may at any time exercise the following rights: access, rectification, erasure (“right to be forgotten”), restriction, objection, portability, and post-mortem directives (French Data Protection Act). To exercise a right or obtain information, write to {{contactEmail}}. In case of disagreement, you may lodge a complaint with the CNIL: www.cnil.fr.

Withdrawal of consent: where processing is based on consent, you may withdraw it at any time without affecting the lawfulness of processing carried out before such withdrawal.

11. Account deletion (Apple Guideline 5.1.1(v))

You may delete your account directly from the Application:
1. Open the “Settings” tab.
2. Tap “Delete my account” in the “Account and data” section.
3. Confirm the permanent deletion.

Upon deletion:
• Your authentication account is deleted immediately.
• Supporting document images you stored in your personal storage area are erased.
• Expense entries you created are deleted, subject to legal and accounting obligations: if an entry has already been validated and integrated into the Publisher's accounting, the accounting record is kept for the legal duration (up to 10 years), dissociated from your identity where technically possible (anonymization of the “reviewer” field, etc.).
• You will no longer be able to log in with this email address without a new registration validated by the Publisher.

You may also write to {{contactEmail}} to request manual deletion or ask any question about this process.

12. Security

Passwords are never stored in clear text: they are hashed by {{hostName}} using proven algorithms. Communications between the application and servers are encrypted via TLS. The database applies Row-Level Security access rules ensuring that an employee only sees their own entries, and that only “manager” / “finance” roles may access others' entries.

13. Cookies and local storage

Mobile application: no third-party cookies. The authentication session is stored locally via the operating system's secure vault (iOS Keychain / Android Keystore via encrypted AsyncStorage).

Website: no advertising cookies, no third-party audience-measurement cookies. The browser only stores your authentication session (localStorage) and your preferences (language); these elements are deleted upon logout.

14. Modifications

The Publisher may update this policy to reflect technical or legal changes. The date of last update is indicated below: {{documentsLastUpdated}}. In case of substantial change, active users are notified via the Application.

15. Contact

For any question regarding this policy or your data: {{contactEmail}}.`;

const termsBody = `These Terms of Service (the “Terms”) govern access to and use of the « {{tradeName}} » service (the “Application”), covering the mobile app (iOS / Android) and the associated website, published by {{companyName}} ({{contactEmail}}).

1. Acceptance

Using the Application implies full and unreserved acceptance of these Terms and of the privacy policy. If you do not accept these terms, do not use the Application.

2. User account

You must provide accurate information when registering. You are responsible for the confidentiality of your credentials and for any action performed from your account. Every account is created or validated by the Publisher. The Publisher may suspend or delete an account in case of serious violation of the Terms or risk to system security.

3. Account deletion

In accordance with Apple App Store Guideline 5.1.1(v), you may delete your account at any time from the “Settings” tab → “Delete my account”. Technical and legal consequences are detailed in section 11 of the privacy policy.

4. Authorized use

The Application is strictly reserved for employees and authorized collaborators of the Publisher, within the framework of internal management of expense reports and related information. You undertake to:
• not undermine the security or integrity of the systems;
• not bypass access controls, RLS, or role limitations;
• not introduce illegal, malicious, fraudulent content or content infringing third-party rights;
• not use the Application for purposes outside the authorized professional scope;
• not extract data en masse by automated means.

5. Your content

You remain the owner of the data and supporting documents you enter. You warrant that you hold the necessary rights to the attachments (notably image rights, copyrights). You grant the Publisher a non-exclusive licence, limited to the duration of the service and the territory of provision, solely to host, back up, process and serve such content within the scope of the service.

6. Third-party services

The Application relies on technical providers (hosting, authentication, App Store / Google Play distribution, AI analysis of supporting documents). Their use is detailed in the privacy policy and subject to their own terms of use.

7. Availability

The Publisher aims for reasonable availability but does not guarantee uninterrupted service. Maintenance operations may cause temporary outages. The Publisher is not responsible for unavailability resulting from third-party providers or force majeure.

8. Intellectual property

The interface, trademarks, logos, code and texts of the Application are the property of the Publisher or its licensors. No intellectual property right is transferred by use of the Application, except for the limited right of use defined herein.

9. Liability

Within the limits of applicable law, the Publisher is not liable for indirect damages or data losses resulting from force majeure, user fault or third-party fault. The Publisher's total liability, if engaged, will be limited to amounts customarily accepted for this type of internal professional service, except in case of gross negligence or intentional misconduct.

10. Notifications and communications

The Publisher may send you, within the framework of the service, operational notifications (expense status, request for additional information, security alert). These communications are non-commercial and do not require additional consent; they may be disabled at the operating system level for push notifications.

11. Termination

You may stop using the Application at any time and delete your account (see section 3). The Publisher may terminate access in case of breach of the Terms, end of the employment contract or commercial relationship.

12. Changes to the Terms

The Publisher may update the Terms to reflect technical, legal or contractual changes. Continued use after notification of a substantial change constitutes acceptance.

13. Governing law and jurisdiction

These Terms are governed by French law. Any dispute falls under the jurisdiction of the courts having jurisdiction over the Publisher's registered office, subject to the mandatory rules of employment law, consumer law and European Union law where applicable.`;

export default {
  sectionTitle: 'Legal information',
  openMentions: 'Legal notice',
  openPrivacy: 'Privacy Policy',
  openTerms: 'Terms of Service',
  footerNotice:
    'These documents are provided for informational purposes and do not replace legal advice. Last updated: {{documentsLastUpdated}}.',
  documents: {
    mentions: {
      title: 'Legal notice',
      body: mentionsBody,
    },
    privacy: {
      title: 'Privacy Policy',
      body: privacyBody,
    },
    terms: {
      title: 'Terms of Service',
      body: termsBody,
    },
  },
};
